# Generated by Django 4.2.23 on 2025-08-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=10)),
                ("age", models.IntegerField()),
                ("bio", models.TextField()),
                ("job_role", models.CharField(max_length=100)),
                ("hobbies", models.JSONField(default=list)),
                ("smoker", models.BooleanField()),
                ("location", models.CharField(max_length=100)),
                ("embedding", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
