# Generated by Django 4.2.23 on 2025-08-20 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Storybook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "page_size",
                    models.CharField(
                        choices=[("A4", "A4"), ("Letter", "Letter")],
                        default="A4",
                        max_length=10,
                    ),
                ),
                ("font_family", models.CharField(default="Helvetica", max_length=100)),
                ("font_size", models.PositiveIntegerField(default=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "index",
                    models.PositiveIntegerField(help_text="Page order in storybook"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("TEXT", "Text"), ("IMAGE", "Image")], max_length=10
                    ),
                ),
                ("text_content", models.TextField(blank=True, null=True)),
                (
                    "image_file",
                    models.ImageField(
                        blank=True, null=True, upload_to="storybook_images/"
                    ),
                ),
                ("image_prompt", models.TextField(blank=True, null=True)),
                (
                    "gen_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DONE", "Done"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "storybook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="storybook.storybook",
                    ),
                ),
            ],
            options={
                "ordering": ["index"],
            },
        ),
    ]
