# Generated by Django 4.2.23 on 2025-08-21 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("storybook", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Export",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pdf_file", models.FileField(upload_to="storybook/exports/")),
                ("page_size", models.CharField(default="A4", max_length=16)),
                ("dpi", models.PositiveIntegerField(default=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("READY", "Ready"),
                            ("ERROR", "Error"),
                        ],
                        default="PENDING",
                        max_length=8,
                    ),
                ),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="ImageJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider", models.CharField(default="hf_sdxl", max_length=50)),
                ("request_payload", models.JSONField(default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="QUEUED",
                        max_length=10,
                    ),
                ),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("cost_cents", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("PASTE", "Paste"), ("PDF", "PDF")], max_length=8
                    ),
                ),
                ("source_text", models.TextField(blank=True)),
                (
                    "source_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="storybook/sources/"
                    ),
                ),
                ("page_count", models.PositiveIntegerField(default=0)),
                ("settings", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("GENERATING", "Generating"),
                            ("READY", "Ready"),
                            ("ERROR", "Error"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="page",
            options={},
        ),
        migrations.AddField(
            model_name="page",
            name="gen_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="image_meta",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="page",
            name="image_prompt_negative",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="seed",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="page",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="page",
            name="gen_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("READY", "Ready"),
                    ("ERROR", "Error"),
                ],
                default="PENDING",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="image_file",
            field=models.ImageField(
                blank=True, null=True, upload_to="storybook/pages/"
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="index",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="page",
            name="kind",
            field=models.CharField(
                choices=[("TEXT", "Text"), ("IMAGE", "Image")], max_length=8
            ),
        ),
        migrations.AddIndex(
            model_name="page",
            index=models.Index(
                fields=["storybook", "index"], name="storybook_p_storybo_da0007_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="page",
            index=models.Index(
                fields=["storybook", "gen_status"],
                name="storybook_p_storybo_660d0d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="page",
            index=models.Index(fields=["kind"], name="storybook_p_kind_7789c4_idx"),
        ),
        migrations.AddField(
            model_name="story",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="imagejob",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="storybook.page",
            ),
        ),
        migrations.AddField(
            model_name="export",
            name="storybook",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exports",
                to="storybook.story",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="storybook",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages",
                to="storybook.story",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="page",
            unique_together={("storybook", "index")},
        ),
        migrations.DeleteModel(
            name="Storybook",
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="storybook_s_created_5645fd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="imagejob",
            index=models.Index(fields=["page"], name="storybook_i_page_id_909b99_idx"),
        ),
        migrations.AddIndex(
            model_name="imagejob",
            index=models.Index(
                fields=["status", "created_at"], name="storybook_i_status_90b1c9_idx"
            ),
        ),
    ]
