# Generated by Django 4.2.23 on 2025-08-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storybook", "0002_export_imagejob_story_alter_page_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
